name: TempBanUI
main: SonsaYT\TempBanUI\TempBan
api: [4.0.0, 5.0.0]
version: 3.0
author: SonsaYT, ClickedTran

commands:
 tempban:
  description: "ยง7Open menu ban player"
  permission: tempban.command
  
 tempcheck:
  description: "ยง7Open menu check"
  permission: tempban.command.check

permissions:
 tempban.command:
  default: op
 tempban.command.check:
  default: op
